---
title: "NMFS_s7_App"
author: "Michael Evans and Meg Evansen"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    css: custom.css
    social: menu
    df_print: paged
    navbar:
    - {title: "", icon: "fa-question-circle fa-lg", align: right, href: "mailto:esa@defenders.org?subject=listings summary"}
    - {title: "", icon: "fa-github fa-lg", align: right, href: "https://github.com/jacob-ogre/ESA_listings_v2"}
    - {title: "CCI", align: right, href: "https://cci-dev.org"}
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cooccur)
library(dplyr)
library(flexdashboard)
library(plotly)
library(reshape2)
library(shiny)
library(vegan)
library(viridis)

good_data <- readRDS(file = 'data/gooddata.rds')
species_x_category <- readRDS(file = "data/speciesxcat.rds")
df <- reactiveVal(good_data)

select_taxa <- selectInput('taxa', 'Select Taxon', unique(good_data$Common.Name), selected = "")
select_category <- selectInput('category', 'Select Work Type', unique(good_data$Category), selected = "")
select_agency <- selectInput('agency', 'Select Federal Agency', unique(good_data$Agency), selected = "")
run_update <- actionButton('update', 'Update')

observeEvent(input$update,
             {d <- filter(good_data,
                          grepl(input$category, Category),
                          grepl(input$taxa, Common.Name),
                          grepl(input$agency, Agency)
             )
             df(d)
             })

discrep_plot <- plot_ly(data = filter(good_data, !is.na(Discrepancy), grepl("Formal", Type))%>%
         group_by(Agency, Discrepancy)%>%
         summarize(count = n(), tot = n_distinct(NMFS.Tracking.Number))%>%
         group_by(Agency)%>%
         mutate(freq = count/sum(count))%>%
         filter(sum(tot) > 20)%>%
         bind_rows(filter(good_data, !is.na(Discrepancy), grepl("Formal", Type),
                          grepl("20[0-9][0-9]", Fiscal.Year))%>%
                     group_by(Discrepancy)%>%
                     summarize(count = n())%>%
                     mutate(freq = count/sum(count), Agency = "All Agencies")),
       type = 'bar', x = ~freq, y = ~Agency, color = ~Discrepancy,
       #text = ~count, textposition = 'outside',
       colors = c(plasma(12)[c(1,4,6)], 'grey', plasma(12)[c(8,10,12)]),
       hoverinfo = 'text',
       text = ~paste(Agency, count, round(freq, 2))
     )%>%
  layout(barmode = 'stack',
         legend = list(orientation = 'h', x = 0.5, y = 100),
         xaxis = list(title = "Proportion of Determinations",
                      titlefont = list(color = 'black'),
                      tickfont = list(color = 'black')),
         yaxis = list(title = "", tickfont = list(color = 'black', size = 10)),
         margin = list(l = 300, r = 0, t = 0))
#TimeLine
output$time_plot <- renderPlotly({
  plot_ly(data = filter(df(), grepl("20[0-16]", Fiscal.Year))%>%
                        group_by(NMFS.Tracking.Number)%>%
          summarize(FY = first(Fiscal.Year), Type = first(Type))%>%
          group_by(FY, Type)%>%
          summarize(count= n()),
        x = ~FY, y = ~count, color = ~ Type, type = 'bar', colors = viridis(5))%>%
  layout(barmode = 'stack',
         xaxis = list(title = "Fiscal Year"),
         yaxis = list(title = "Consultations"),
         legend = list(x = 0, y = 1),
         margin = list(b = 100))
})

#Frequency of Consultations by Work Category
cat_dt <- filter(good_data, grepl(".", Category), grepl("20[0-9][0-9]", Fiscal.Year))%>%
  group_by(NMFS.Tracking.Number)%>%
  summarize(Category = first(Category))%>%
  group_by(Category)%>%
  summarize(count = n())%>%
  top_n(10, count)

cat_vec <- cat_dt$count
names(cat_vec) <- cat_dt$Category

output$category_plot <- renderPlotly({
  plot_ly(data = cat_dt, y = ~Category, x = ~count, type= "bar", orientation = 'h',
        text = ~Category, textposition = c(rep('outside', 9), 'inside'),
        textfont = list(color = c(rep('black', 9), 'white')))%>%
  layout(title = "Work Type",
         yaxis = list(categoryorder = 'array',
                      categoryarray = names(sort(cat_vec)),
                      title = "",
                      showticklabels = FALSE),
         xaxis = list(title = "")
         )
})

#Frequency of Consultations by Agency
ag_dt <- filter(good_data, grepl(".", Agency), grepl("20[0-9][0-9]", Fiscal.Year))%>%
  group_by(NMFS.Tracking.Number)%>%
  summarize(Agency = first(Agency))%>%
  group_by(Agency)%>%
  summarize(count = n())%>%
  top_n(10, count)

ag_vec <- ag_dt$count
names(ag_vec) <- ag_dt$Agency

output$agency_plot <- renderPlotly({
  plot_ly(data = ag_dt, y = ~Agency, x = ~count, type= "bar", orientation = 'h',
        text = ~Agency, textposition = c('inside', rep('outside', 9)),
        textfont = list(color = c('white', rep('black', 9))))%>%
  layout(title = "Agencies",
         yaxis = list(categoryorder = 'array',
                      categoryarray = names(sort(ag_vec)),
                      title = "",
                      showticklabels = FALSE),
         xaxis = list(title = "# consultations")
  )
})

#  Frequency of Consultations by Species
sp_dt <- filter(good_data, grepl(".", Common.Name), grepl("20[0-9][0-9]", Fiscal.Year))%>%
  group_by(Common.Name)%>%
  summarize(count = length(unique(NMFS.Tracking.Number)))%>%
  top_n(10, count)

sp_vec <- sp_dt$count
names(sp_vec) <- sp_dt$Common.Name

output$species_plot <- renderPlotly({
  plot_ly(data = sp_dt, y = ~Common.Name, x = ~count, type= "bar", orientation = 'h',
        text = ~Common.Name,
        #textposition = 'outside',
        #textfont = list(color = 'black', size = 14)
        textposition = c('inside', rep('outside', 3), 'inside', rep('outside', 5)),
        textfont = list(color = c('white', rep('black', 3), 'white', rep('black', 5)), size = 14)
        )%>%
  layout(title = "Species",
         titlefont = list(color = 'black', size = 16),
         yaxis = list(categoryorder = 'array',
                      categoryarray = names(sort(sp_vec)),
                      title = "",
                      showticklabels = FALSE),
         xaxis = list(title = "", range = c(0, 15000),
                      showgrid = FALSE,
                      tickfont = list(color = 'black', size = 12))
  )
})

###CREATE MATRICES AND PERMUTATION TESTS FOR SPECIES BY CATEGORY HEATMAP
permtest <- permatfull(species_x_category, fixedmar = 'both', mtype = "count", times = 1000)
permtests <- lapply(permtest$perm, function(i){return(i >= species_x_category)})
permeff <- species_x_category - Reduce('+', permtest$perm)/1000
permstats <- Reduce('+', permtests)/1000


spbycat_plot <- plot_ly(z = permeff, #species_x_category
            x = ~colnames(species_x_category),
            y = ~rownames(species_x_category), type = 'heatmap',
            zmin = -5, zmax = 10
            )%>%
      layout(margin = list(b = 100, l = 200),
             xaxis = list(title = "",
                          tickfont = list(color = 'black')),
             yaxis = list(title = "",
                          tickfont = list(color = 'black')))


```

Basic
=====

### Discrepancies

```{r discrep_txt, echo = FALSE}
fluidPage(
  fluidRow(
    column(3,
           p("Federal agencies get to propose a determination for each species that may be affected
             by their actions.  NMFS may agree or disagree with these proposals.  We scored these
             discrepancies by the severity of the disagreement with -3 indicating severe underestimation
             of effects by the action agency, and 3 indicating severe overestimation.")
           ),
    column(1),
    column(8, discrep_plot)
  )
)
```

### Selectors {data-height=1400}
```{r selectors, echo = FALSE}
#fluidPage(
  fluidRow(
    column(2,
           select_taxa,
           select_category,
           select_agency,
           run_update
           ),
    column(1),
    column(9,
           plotlyOutput("time_plot"),
           plotlyOutput("agency_plot"),
           plotlyOutput("category_plot"),
           plotlyOutput("species_plot")
    )
  )
#)

```

### Species x work type matrix
```{r matrix, echo = FALSE}
fluidPage(
  fluidRow(
    column(8, spbycat_plot),
    column(1),
    column(3, p('Certain types of proposed actions may be more likely to jeopardize particular listed species.
                This heatmap illustrated which combinations of work types and species resulted in more (yellow)
                or fewer (purple) jeopardy determinations than would be expected by random chance.'))
  )
)
```

Advanced
========
